---
# vim: set ft=ansible:


apt_packages_to_remove:
- puppet
- puppet-common
- chef
- chef-zero

apt_mandatory_packages:
- apt-transport-https
- aria2
- autoconf
- autojump
- automake
- build-essential
- ca-certificates
- ccache
- cookiecutter
- curl
- exuberant-ctags
- g++
- gcc
- git
- golang-go
- htop
- httpie
- iftop
- iotop
- jq
- keychain
- libapt-pkg-dev
- libbz2-dev
- libncurses5-dev
- libncursesw5-dev
- libreadline-dev
- libsqlite3-dev
- libssl-dev
- libtool
- llvm
- locales
- ncurses-term
- openssh-client
- par
- pkg-config
- python
- python3
- python3-dev
- python3-pip
- python3-setuptools
- python3-virtualenv
- python3-wheel
- python-dev
- python-pip
- python-pip-whl
- python-setuptools
- python-virtualenv
- python-wheel
- rsync
- ruby
- ruby-dev
- shellcheck
- silversearcher-ag
- software-properties-common
- stow
- tig
- tmux
- tox
- vim
- wget
- wget
- xz-utils
- yamllint
- zlib1g-dev
- zsh

locales:
- en_US.UTF-8
- ru_RU.UTF-8

tmux_deb_link: http://no.archive.ubuntu.com/ubuntu/pool/main/t/tmux/tmux_2.3-4ubuntu1_amd64.deb

pyenv_plugins:
- name: pyenv-virtualenv
  repo: https://github.com/yyuu/pyenv-virtualenv.git
- name: pyenv-update
  repo: https://github.com/yyuu/pyenv-update.git
- name: pyenv-doctor
  repo: https://github.com/yyuu/pyenv-doctor.git
- name: pyenv-ccache
  repo: https://github.com/yyuu/pyenv-ccache.git
- name: pyenv-which-ext
  repo: https://github.com/yyuu/pyenv-which-ext.git
- name: pyenv-default-packages
  repo: https://github.com/jawshooah/pyenv-default-packages.git

stow_dotfiles:
- ag
- aria2
- ctags
- git
- nodejs
- python
- scripts
- tmux
- vim

pip3_packages: {}
pip2_packages:
  tmuxp: latest
  "docker-compose": latest
